### ISSUE TITLE
Remove deprecated remoting protocols

### ISSUE THREAD

**Issue by rtyler** [CodeValet/codevalet#19]
https://sentry.io/codevalet/codevalet/issues/334256000/

```
This Jenkins instance uses deprecated Remoting protocols: JNLP-connect,JNLP2-connectIt may impact stability of the instance. If newer protocol versions are supported by all system components (agents, CLI and other clients), it is highly recommended to disable the deprecated protocols.
```

**Comment by rtyler** [comment]
There is something about this still showing up. I launched a brand new `berriedale` instance, and that immediately logged this error.

I wonder if perhaps this is being logged _before_ any `init.groovy.d` scripts are being run?

**Comment by daniel-beck** [comment]
Log message on startup removed in https://github.com/jenkinsci/jenkins/pull/3190

> I wonder if perhaps this is being logged _before_ any `init.groovy.d` scripts are being run?

Both seem to be launched in parallel at the same init milestone (after jobs are loaded).

**Comment by rtyler** [comment]
Thanks for the catch @daniel-beck, I'll mark this issue as resolved in Sentry and that should let me know if this regresses

**Comment by rtyler** [comment]
https://sentry.io/codevalet/codevalet/issues/411979391/
