### ISSUE TITLE
Instances should set the default Pipeline Docker Label

### ISSUE THREAD

**Issue by rtyler** [CodeValet/codevalet#33]
To you know, `docker`.

Now that there are multiple agents available, I don't want the wrong one to be chosen for a docker-based workload

**Comment by abayer** [comment]
You're using Declarative? If so, then you can set the `org.jenkinsci.plugins.pipeline.modeldefinition.config.GlobalConfig` extension of `GlobalConfiguration`...like, maybe:
```
import jenkins.model.GlobalConfiguration
import org.jenkinsci.plugins.pipeline.modeldefinition.config.GlobalConfig

GlobalConfig c = GlobalConfiguration.all().find { it instanceof GlobalConfig }
if (c != null) {
  c.setDockerLabel("docker")
}
```
I think that'd work?

**Comment by rtyler** [comment]
Most interesting, will give it a try!

**Comment by rtyler** [comment]
I'll be damned, it works!

**Comment by abayer** [comment]
yaaaay!
